###############################################################################
# NFC Configuration for Itel S23+ (S681LN)
# Author: anothernop

###############################################################################
# Application options
NFC_DEBUG_ENABLED=1

###############################################################################
# File used for NFA storage
NFA_STORAGE="/data/nfc"

###############################################################################
# Force UICC to only listen to the following technology(s).
UICC_LISTEN_TECH_MASK=0x07

###############################################################################
# AID for Empty Select command
AID_MATCHING_MODE=0x01

###############################################################################
# Bail out mode
#  If set to 1, NFCC is using bail out mode for either Type A or Type B poll.
NFA_PROPRIETARY_CFG={08, FF, FF, 06, 81, 80, 70, FF, FF}

###############################################################################
# White list of Hosts
DEVICE_HOST_WHITE_LIST={C0}

###############################################################################
# Vendor Specific Proprietary Protocol & Discovery Configuration
NFA_PROPRIETARY_CFG={05, FF, FF, 06, 81, 80, 70, FF, FF}

###############################################################################
# Choose the presence-check algorithm for type-4 tag.
PRESENCE_CHECK_ALGORITHM=1

###############################################################################
# Force tag polling for the following technology(s).
POLLING_TECH_MASK=0xEF

###############################################################################
# Maximum Number of Credits to be allowed by the NFCC
MAX_RF_DATA_CREDITS=1

###############################################################################
# Screen state
SCREEN_OFF_POWER_STATE=0x00

###############################################################################
# NXP vendor configurations
NXP_NFC_CHIP=pn54x
NXP_CORE_CONF_EXTN={20, 02, 05, 01, A0, 44, 01, 00}
NXP_CORE_STANDBY={2F, 00, 01, 01}

###############################################################################
# Enable or Disable RF_STATUS_UPDATE to EseHal module
RF_STATUS_UPDATE_ENABLE=1